#!/usr/bin/env bash
# Auto-generated by bhaskera/setup.sh - do not edit manually
# Source this at the top of your SLURM job scripts

# Load CUDA via spack or module
if [[ -f "/home/apps/SPACK/spack/share/spack/setup-env.sh" ]] && [[ -n "" ]]; then
    source "/home/apps/SPACK/spack/share/spack/setup-env.sh" 2>/dev/null || true
    spack load  2>/dev/null || true
elif command -v module &>/dev/null && [[ -n "12.0" ]]; then
    module load cuda/12.0 2>/dev/null || true
fi

source "/mnt/disk1/slakshna/Bhaskera/.venv/bin/activate"
